# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: likes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'likes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blikes.proto\x12\x08likes.v1\"\"\n\x04Like\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\t\"#\n\x11\x43reateLikeRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\"\x1c\n\x0eGetLikeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x12\n\x10ListLikesRequest\"2\n\x11ListLikesResponse\x12\x1d\n\x05likes\x18\x01 \x03(\x0b\x32\x0e.likes.v1.Like\",\n\x0cLikeResponse\x12\x1c\n\x04like\x18\x01 \x01(\x0b\x32\x0e.likes.v1.Like\"\x1f\n\x11\x44\x65leteLikeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteLikeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9d\x02\n\x0cLikesService\x12\x41\n\nCreateLike\x12\x1b.likes.v1.CreateLikeRequest\x1a\x16.likes.v1.LikeResponse\x12;\n\x07GetLike\x12\x18.likes.v1.GetLikeRequest\x1a\x16.likes.v1.LikeResponse\x12\x44\n\tListLikes\x12\x1a.likes.v1.ListLikesRequest\x1a\x1b.likes.v1.ListLikesResponse\x12G\n\nDeleteLike\x12\x1b.likes.v1.DeleteLikeRequest\x1a\x1c.likes.v1.DeleteLikeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'likes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIKE']._serialized_start=25
  _globals['_LIKE']._serialized_end=59
  _globals['_CREATELIKEREQUEST']._serialized_start=61
  _globals['_CREATELIKEREQUEST']._serialized_end=96
  _globals['_GETLIKEREQUEST']._serialized_start=98
  _globals['_GETLIKEREQUEST']._serialized_end=126
  _globals['_LISTLIKESREQUEST']._serialized_start=128
  _globals['_LISTLIKESREQUEST']._serialized_end=146
  _globals['_LISTLIKESRESPONSE']._serialized_start=148
  _globals['_LISTLIKESRESPONSE']._serialized_end=198
  _globals['_LIKERESPONSE']._serialized_start=200
  _globals['_LIKERESPONSE']._serialized_end=244
  _globals['_DELETELIKEREQUEST']._serialized_start=246
  _globals['_DELETELIKEREQUEST']._serialized_end=277
  _globals['_DELETELIKERESPONSE']._serialized_start=279
  _globals['_DELETELIKERESPONSE']._serialized_end=316
  _globals['_LIKESSERVICE']._serialized_start=319
  _globals['_LIKESSERVICE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
