apiVersion: v1
kind: Service
metadata:
  name: likes-svc-s03
  labels:
    app: likes-app
spec:
  selector:
    app: likes-app
    component: likes-svc
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP