# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import likes_pb2 as likes__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in likes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LikesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLike = channel.unary_unary(
                '/likes.v1.LikesService/CreateLike',
                request_serializer=likes__pb2.CreateLikeRequest.SerializeToString,
                response_deserializer=likes__pb2.LikeResponse.FromString,
                _registered_method=True)
        self.GetLike = channel.unary_unary(
                '/likes.v1.LikesService/GetLike',
                request_serializer=likes__pb2.GetLikeRequest.SerializeToString,
                response_deserializer=likes__pb2.LikeResponse.FromString,
                _registered_method=True)
        self.ListLikes = channel.unary_unary(
                '/likes.v1.LikesService/ListLikes',
                request_serializer=likes__pb2.ListLikesRequest.SerializeToString,
                response_deserializer=likes__pb2.ListLikesResponse.FromString,
                _registered_method=True)
        self.DeleteLike = channel.unary_unary(
                '/likes.v1.LikesService/DeleteLike',
                request_serializer=likes__pb2.DeleteLikeRequest.SerializeToString,
                response_deserializer=likes__pb2.DeleteLikeResponse.FromString,
                _registered_method=True)


class LikesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LikesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLike': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLike,
                    request_deserializer=likes__pb2.CreateLikeRequest.FromString,
                    response_serializer=likes__pb2.LikeResponse.SerializeToString,
            ),
            'GetLike': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLike,
                    request_deserializer=likes__pb2.GetLikeRequest.FromString,
                    response_serializer=likes__pb2.LikeResponse.SerializeToString,
            ),
            'ListLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLikes,
                    request_deserializer=likes__pb2.ListLikesRequest.FromString,
                    response_serializer=likes__pb2.ListLikesResponse.SerializeToString,
            ),
            'DeleteLike': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLike,
                    request_deserializer=likes__pb2.DeleteLikeRequest.FromString,
                    response_serializer=likes__pb2.DeleteLikeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likes.v1.LikesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likes.v1.LikesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LikesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v1.LikesService/CreateLike',
            likes__pb2.CreateLikeRequest.SerializeToString,
            likes__pb2.LikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v1.LikesService/GetLike',
            likes__pb2.GetLikeRequest.SerializeToString,
            likes__pb2.LikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v1.LikesService/ListLikes',
            likes__pb2.ListLikesRequest.SerializeToString,
            likes__pb2.ListLikesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likes.v1.LikesService/DeleteLike',
            likes__pb2.DeleteLikeRequest.SerializeToString,
            likes__pb2.DeleteLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
